import React from 'react'
import './PrivacyView.scss'

class PrivacyView extends React.Component {

    render() {
        return (
            <div className='privacyView__container'>
                <div className='privacyView__content'>
                    <content-row className="privacy">
                        <div translate="AS_PRIVACY_POLICY_HTML" className="ng-scope">
                            <h1>Privacy policy of Axel Springer Crowd</h1>
                            <p>We are very pleased about your interest in Axel Springer Crowd. To be able to offer Axel Springer Crowd, we of course require certain data about you. We take the protection of personal data very seriously and always process it in compliance with applicable data protection regulations, in particular the European Union General Data Protection Regulation (GDPR). With this privacy policy, we aim to fully inform you about how, why and to what extent we process personal data, and what your rights are as a data subject.</p>
                            <h2>1. Data controller and general information</h2>
                            <p>Your data will be processed by Axel Springer Ideas Engineering GmbH, Axel Springer Str. 65, 10969 Berlin, phone: +49 2591 71000, email: crowd@asideas.de (service provider for the purposes of the Act for Telecommunication Media Services (TMG) and data controller for the purposes of the General Data Protection Regulation (GDPR).</p>
                            <p>When we use terms such as “we” or “us”, this is who we are referring to.</p>
                            <p>We consider Axel Springer Crowd to mean any sub-pages, content and functions (for instance discussion forums, prize draws) present in this document https://crowd.asideas.de .Individual elements of Axel Springer Crowd are also referred to as “online services” below. The same is meant wherever we refer to a website.</p>
                            <p>Our services are intended for the general public, and not for children. We do not knowingly collect personal data from users who are regarded as children under applicable national legislation.</p>
                            <h2>2. Collection and processing of personal data</h2>
                            <p>You can usually use online services that do not require payment or registration without providing personal data. In certain cases, however, we may process personal data listed under point 3. This is only done as is necessary to provide a functioning website our content and our services. We also process personal data in connection with the use of Axel Springer Crowd insofar as you provide such data voluntarily, for instance for the purpose of registration, a prize draw, sending us an enquiry, submitting an application to us, subscribing to a publication, or some other legal basis (see point 4). If you do not wish to provide personal data, you will unfortunately not be able to make use of our services or will only be able to use them to a limited degree.</p>
                            <h2>3. Categories of processed data</h2>
                            <p>As soon as you make use of Axel Springer Crowd, our system will automatically collect information from the computing device accessing the service. The following data may be collected by way of example:</p>
                            <ul>
                                <li>Information about the browser type and version used</li>
                                <li>The operating system of the user</li>
                                <li>Date and time of the access</li>
                                <li>Web analysis data / pseudonymised user profiles (cookie ID, ad ID, etc.)</li>
                                <li>Websites from which the users access our website</li>
                                <li>Websites that the users access from our website</li>
                            </ul>
                            <p>We also process the following personal data insofar as there is a contract in effect between you and us or if you have provided us with the data by other means:</p>
                            <ul>
                                <li>Contact details (telephone number, email address)</li>
                                <li>Account details with password</li>
                                <li>Comments, articles, etc.</li>
                            </ul>
                            <h2>4. Legal basis and purposes of processing</h2>
                            <p>We only process your data on the basis of one or several potential legal bases.</p>
                            <p>Pursuant to the GDPR, personal data may be processed in particular under the terms of a contract or to perform pre-contractual activities, if consent is provided, if there is a legitimate interest or compelling statutory cause, or if it becomes necessary to protect vital or public interests.</p>
                            <p>For certain content or services to be provided on our website, users must sign in with a user account. Registration is required in order to obtain a user account. This data is collected and processed as described above for the purpose of performing a user agreement between us and you pursuant to Art. 6 para. 1 point b GDPR.</p>
                            <p>Your email address, which is collected during registration or during the performance of the contract, is also used by us to inform you about similar products or services that we offer, about existing subscriptions, and in general about Axel Springer Crowd. In this case, your email address will be processed on the basis of our legitimate interest in marketing our goods and services (Art. 6 para. 1 point f GDPR). You can withdraw your consent at any time for the use of your e-mail address for such purposes in writing or in text form [email address and postal address] with effect for the future without incurring any transmission costs beyond the base costs imposed by your provider.</p>
                            <p>We also use your email address to send you our newsletter if you have given us your prior express consent to receive a newsletter and/or marketing emails in this connection. In this case, we will process your email address in order to be able to send you the newsletter as requested (Art. 6 para. 1 point a GDPR). You can withdraw your consent at any time for the use of your email address for such purposes in writing or via electronic text communication media at crowd@asideas.de or Axel-Springer-Str. 65 in 10969 Berlin with effect for the future.</p>
                            <p>On the internet, every device requires a unique address to transmit data, known as an IP address. This IP address must be stored, even if only temporarily, for technical reasons in order to enable the website to be downloaded to the user’s end device. Unless stipulated otherwise in this privacy policy, we shorten IP addresses prior to any processing and only process IP addresses in anonymised form. On the basis of the truncated IP address, we can display content of regional interest on all our websites that are accessed from a particular region. Geolocation, which is the ability to determine where a certain visitor is located, is fundamentally only applied with the use of the anonymised IP address and only allows geographical location down to specific federal states or regions. The geographical information acquired in this manner cannot under any circumstances be used to establish a user’s specific location. Our servers will also store your IP address for a period of 14 days for internal security purposes (Art. 6 para. 1 point f GDPR).</p>
                            <p>On our website and on individual blogs, we offer a comment function for which personal data that you enter voluntarily is stored. If you have provided consent for this purpose, you will be able to submit and subscribe to comments on our website in some cases. The same applies to surveys that you participate in. If you wish to publish a comment, you will need to complete the fields for this purpose. You can also post under a pseudonym. If you do not complete the fields, you cannot publish a comment. We collect and process the data that you provide in order to publish your comment as requested (Art. 6 para. 1 point b GDPR). In particular, we require your email address so that we can contact you about any objections to your comment and allow you make a statement in this connection (Art. 6 para. 1 point c GDPR).</p>
                            <p>For processing activities encompassed by none or several of the aforementioned legal bases, processing is performed insofar as it is necessary to uphold a legitimate interest and insofar as this interest is not outweighed by your interests, fundamental rights or freedoms following a thorough consideration of the interests as a whole. A legitimate interest can be assumed if the data subject is a customer of the data controller. If personal data is processed on this basis, our particular legitimate interest here is in the performance of our business activities for the benefit of all of our employees and our shareholders.</p>
                            <p>Our legitimate interest in being able to offer you tailored products, informing you about our products, news and quality features, and continuously improving our services and products with a view to increasing our revenue provides the legal basis for processing by means of web/app analysis. See point 9 for details on Web analytics tools.</p>
                            <p>You can object to processing performed on the basis of a legitimate interest at any time (see point 14).</p>
                            <p>If data is processed for a purpose other than that specified upon collection, a compatibility test is performed pursuant to Art. 6 para. 4 of the GDPR. Continued processing is then only permitted if the original purpose is compatible with the new purpose or if this processing is permitted on a specific legal basis. Recognised compatible purposes include the establishment, exercise or defence of legal claims under civil law, unless outweighed by an interest of the data subject, in which case we will inform you about the change in purpose. If the new purpose is not compatible with the purpose specified upon collection, the data will be collected again on a new legal basis. We will also inform you about the change in purpose in this case.</p>
                            <h2>5. Place of processing</h2>
                            <p>We personally will not transmit your personal data to countries outside of the European Economic Area, except where permitted by the GDPR. We cannot know and cannot influence whether third parties with whom you have concluded a separate contractual agreement (for instance with Facebook, if you have a Facebook account) transmit data to countries outside of the European Economic Area.</p>
                            <h2>6. Origin of data</h2>
                            <p>In certain cases, we also receive data because you have consented to its transmission to us.</p>
                            <p><b>Facebook Connect</b></p>
                            <p>You can also log into Axel Springer Crowd using a Facebook account.</p>
                            <p>Facebook Connect is a service of Facebook Ireland Limited, 4 Grand Canal Square, Dublin 2, Ireland. The use of Facebook Connect is governed by the Data Policy and Terms of Service of Facebook. If you choose to register using your Facebook account, you will first be forwarded directly to Facebook, where Facebook will ask you to enter your account details and log in to or register with Facebook. If you are already logged into Facebook at that time, this login request will be skipped. Important: We do not receive any account details during this process. When logging in through Facebook Connect, your Facebook profile information and “public information” as defined by Facebook (<a href="https://www.facebook.com/about/privacy/your-info/">https://www.facebook.com/about/privacy/your-info/</a>), i. e. information that you have made publicly available or have consented to disclosing to us for the relevant application) will be transmitted from your Facebook profile to us. “Public” for the purposes of Facebook refers to information that anyone, even outside of Facebook, can access. This includes your name, profile image, cover image, gender, networks, user name (Facebook URL) and user ID number (Facebook ID). Conversely, data may also be sent by us to your Facebook profile. If you log in to our service via Facebook Connect, we will store and process your data as transmitted to us for the purpose of registration.
                            </p>
                            <h2>7. Transmission of your data to third parties</h2>
                            <p>We will only transmit your personal data to third parties if transmission is required to comply with our contractual obligations to you if this evidently needs to be done through or jointly with another provider (e. g. partnerships), if we are permitted or required by law to transmit the data in any other fashion, or if you have provided us with the corresponding consent.</p>
                            <p>To provide our service, selected personal data may be transmitted to certain departments within our company, including employees of the Accounting, Product Management, Marketing and IT departments.</p>
                            <p>In certain cases we also employ external service providers or affiliates commissioned by us to process data on our behalf on the basis of instructions. We ensure that such service providers are contractually bound by the strict terms of the GDPR as data processors and that they are prohibited from using your data for any other purposes. Data processors employed by us provide the following services in particular: hosting, sending newsletters, maintenance and support and web/app analytics tools. See point 9 for details on Web analytics tools.</p>
                            <p>Data is transmitted to data processors on the basis of Art. 28 para. 1 of the GDPR, and also on the basis of our legitimate interest in economic and technical advantages afforded by the employment of specialist data processors as permitted by Art. 6 para. 1 point f of the GDPR.</p>
                            <p>Insofar as we are required to do so by law or are permitted to do so under data protection law, we will transmit personal data to public authorities such as the police or public prosecution service (Art. 6 para. 1 point c GDPR). This data is transmitted on the basis of our legitimate interest in preventing abuse, prosecuting criminal acts and securing, establishing and enforcing legal claims, unless outweighed by your rights and interests in the protection of your personal data, Art. 6 para. 1 point f of the GDPR.</p>
                            <h2>8. Cookies and similar technologies</h2>
                            <p>We make use of cookies, which are small files that your browser deposits in a folder designated for this purpose on your device. This makes it possible, for instance, to determine whether you have visited a website before. With your consent, cookies can also be used to store account details for an online service, meaning that you do not need to enter these account details every time you open the website. Many cookies contain what is known as a “cookie ID”, which is a unique identifier for the cookie. It consists of a string of characters which websites and servers can associate with the specific web browser in which the cookie has been stored. This enables visited websites and servers to differentiate between the specific browser of the data subject and other web browsers containing different cookies. A specific web browser can be recognised and identified using the unique cookie ID.</p>
                            <p>We use two types of cookies. The first are technically necessary cookies, without which the functionality of our website would be limited. The second is the optional cookie, which we use to make our website more user-friendly. The user data collected in technically necessary cookies is not used to create user profiles. Analysis cookies are used to improve the quality of our website and its content. We use analysis cookies to ascertain how the website is being used, allowing us to continuously optimise our services. Further information on individual analysis services can be found under point 9 of this privacy policy.</p>
                            <p>Advertisements are usually delivered by third-party providers. These may use information on your visits, provided that your device configuration allows this, so that advertisements on products and services that may be of interest to you are displayed. Specific contact details such as your name, postal address, email address or telephone number will not be transmitted under any circumstances.</p>
                            <p>You can prevent cookies from being set by us at any time by configuring the web browser that you are using, which represents your objection to the setting of cookies. Previously set cookies can also be deleted at any time using a web browser or another software solution. This is possible in all standard web browsers. If you deactivate cookies in your chosen web browser, it may not be possible for you to use all of the functions of our website in full.</p>
                            <p>Cookies cannot be used to identify you personally. In any case, the use of cookies is justified on the basis of our legitimate interest in designing the website to meet demand and in conducting statistical analyses of Axel Springer Crowd (Art. 6 para. 1 point f GDPR).</p>
                            <h2>9. Web analytics tools</h2>
                            <p>In order to continuously improve our services and adapt them to the interests of our users, and in order to display usage-based online advertising, we make use of a number of analysis services that collect and analyse data on our website on our behalf. Where these service providers are not controllers within the meaning of data privacy law, they always process the pseudonymised user data under instruction on the basis of a data processing agreement. You can deactivate the individual analysis services at any time with effect for the future. Specific information on the individual analysis services employed by us can be found below:</p>
                            <h3>Google Analytics</h3>
                            <p>We have integrated Google Analytics (with anonymisation function). Google Analytics is a web analytics tool from Google Ireland Limited („Google“), Gordon House, Barrow Street, Dublin 4, Irland. Web analytics is the collection and analysis of data about the behaviour of website visitors. A web analytics tool collects, among other things, data about the website from which a data subject arrived at particular website (known as the referrer), the subpages of the website that were accessed and how often and for how long a subpage was looked at. Web analytics is primarily used to optimise a website and for cost-benefit analysis of online advertising.</p>
                            <p>For web analytics via Google Analytics we use the suffix "_gat._anonymizeIp". This means that the IP address of the data subject's Internet connection is truncated and anonymised by Google if our websites are accessed from a Member State of the European Union or from a contracting state of the Agreement on the European Economic Area.</p>
                            <p>The purpose of the Google Analytics component is to analyse visitor flows on our website. Among other things, Google uses the data and information obtained to analyse the use of our website, to compile online reports for us detailing activities on our websites, and to provide other services connected with the use of our website.</p>
                            <p>Google Analytics sets a cookie on the data subject's IT system. An explanation of what cookies are is provided above. Setting the cookie enables Google to analyse the use of our website. Each time one of the individual pages of this website is accessed, which is operated by us and incorporates a Google Analytics component, the web browser on the data subject's IT system is automatically prompted by the respective Google Analytics component to transmit data to Google for the purposes of online analysis. As part of this technical process, Google gains knowledge of personal data, such as the IP address of the data subject, which Google uses, among other things, to track the origin of visitors and clicks, and to subsequently enable commission to be calculated.</p>
                            <p>Using the cookie, personal information is stored, such as time and location of access and the frequency of visits to our website by the data subject. Each time our website is visited, this personal data, including the IP address of the Internet connection used by the data subject, is transferred to Google. This personal data is stored by Google. In some cases, Google may share the personal data collected through this technical process with third parties.</p>
                            <p>The data subject can prevent cookies from being set by our website at any time, as explained above, by configuring the web browser they use to block cookies. Configuring the web browser in this way will also prevent Google from setting a cookie on the data subject's IT system. A cookie already set by Google Analytics can also be deleted at any time using a web browser or another software solution.</p>
                            <p>It is also possible for the data subject to opt out of Google Analytics collecting data generated by the Google Analytics cookie in relation to use of this website and processing such data, thereby preventing this. To do so, the data subject must download and install a browser add-on using the link <a href="http://tools.google.com/dlpage/gaoptout?hl=en">http://tools.google.com/dlpage/gaoptout?hl=en</a> This browser add-on notifies Google Analytics via JavaScript that no data or information about the website visits is allowed to be transmitted to Google Analytics. Google regards installation of the browser add-on as opting out. If the data subject's IT system is erased, formatted or re-installed at a later date, the browser add-on must be re-installed by the data subject to block Google Analytics. If the browser add-on is uninstalled or disabled by the data subject or someone else within the data subject's sphere of control, the browser add-on can be re-installed or enabled again.<br/>
                            </p>
                            <p>More information and the current Google privacy policy is available at <a href="https://policies.google.com/privacy?hl=en&amp;gl=en">https://policies.google.com/privacy?hl=en&amp;gl=en</a> and at <a href="https://www.google.com/analytics/terms/gb.html">https://www.google.com/analytics/terms/gb.html</a>. Further details on Google Analytics can be found at the link <a href="https://www.google.com/intl/en_en/analytics/">https://www.google.com/intl/en_en/analytics/</a>.
                            </p>
                            <h2>10. Social networks</h2>
                            <p>You can also find us on the social networks of external companies such as Facebook and Twitter. We have also integrated certain functions of these networks into our own online services. However, it is only possible to use either of them if you are registered and logged in to the relevant social network. Please note that use of each of the social networks is fundamentally governed by the relevant terms of service and privacy policies of the respective companies and we have no influence over these. However, we will be happy to explain how such networks process your personal data in this connection.</p>
                            <p>On smartphones and tablets, the mentioned services are frequently implemented not in the form of plug-ins, but through the use of the device’s integrated “share” function. Depending on how this is configured, it may also be possible to transmit information to other social media service providers. Please refer to your device’s manual for more details on this.</p>
                            <h3>Facebook</h3>
                            <p>We have integrated components of Facebook into this website. Facebook is a social network.</p>
                            <p>A social network is an Internet-based social meeting place – an online community that usually allows users to communicate with each other and to interact in virtual space. A social network can serve as a platform for exchanging opinions and experiences or enables the online community to provide personal or company-related information. Facebook enables users of the social network to create private profiles, upload photos and network via friendship requests, among other things.</p>
                            <p>Facebook is operated by Facebook, Inc., 1 Hacker Way, Menlo Park, CA 94025, USA. The controller responsible for the processing of personal data, if a data subject lives outside the USA or Canada, is Facebook Ireland Ltd., 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Ireland.</p>
                            <p>Each time one of the individual pages of this website is accessed, which is operated by us and incorporates a Facebook component (Facebook plug-in), the web browser on the data subject's IT system is automatically prompted by the respective Facebook component to download a representation of the corresponding Facebook component from Facebook. An overview of all Facebook plug-ins is available at <a href="https://developers.facebook.com/docs/plugins/">https://developers.facebook.com/docs/plugins/</a>. As part of this technical process, Facebook is informed about which specific subpage of our website is visited by the data subject.
                            </p>
                            <p>If the data subject is signed in to Facebook at the same time, Facebook recognises which specific subpage of our website the data subject visits each time the data subject accesses our website and for the entire duration of the respective visit. This information is collected by the Facebook component and assigned by Facebook to the respective Facebook account of the data subject. If the data subject clicks one of the Facebook buttons integrated into our website, for example the "Like" button, or the data subject makes a comment, Facebook assigns this information to the personal Facebook user account of the data subject and stores this personal data.</p>
                            <p>Facebook is always informed via the Facebook component that the data subject has visited our website if the data subject is signed in to Facebook at the same time as accessing our website; this takes place regardless of whether the data subject clicks the Facebook component or not. If the data subject does not want this information to be transmitted to Facebook, they can prevent it from being transmitted by signing out of their Facebook account before accessing our website.</p>
                            <p>The privacy policy published by Facebook, available at <a href="https://facebook.com/about/privacy/">https://facebook.com/about/privacy/</a>, provides information about the collection, processing and use of personal data by Facebook. It also explains what setting options Facebook offers to protect the privacy of data subjects. In addition, various applications are available that make it possible to suppress data transmission to Facebook. Such applications can be used by the data subject to suppress data transmission to Facebook.
                            </p>
                            <h3>Instagram</h3>
                            <p>We use components of the Instagram service. Instagram is a service that can be qualified as an audiovisual platform, allowing users to share photos and videos and to redistribute such data on other social networks. Instagram is operated by Instagram LLC, 1 Hacker Way, Building 14 First Floor, Menlo Park, CA, USA. Each time one of the individual pages of this website is accessed, which incorporates an Instagram component (Insta button), Instagram is informed about which specific subpage of our website is visited by the data subject. If you are signed in to Instagram at the same time, each time you access our website and for the entire duration of your visit, Instagram recognises which specific subpage was visited. This information is collected by the Instagram component and assigned to your Instagram account by Instagram. If you press one of the Instagram buttons integrated into our website, the data and information thus transmitted is assigned to your personal Instagram user account and stored and processed by Instagram. Instagram is always informed via the Instagram component that you have visited our website if you are signed in to Instagram at the same time as accessing our website; this takes place regardless of whether you click the Instagram component or not. If you do want this information to be transmitted to Instagram, you can prevent it from being transmitted by signing out of your Instagram account before accessing our website. More information and the current Instagram privacy policy is available at <a href="https://help.instagram.com/155833707900388">https://help.instagram.com/155833707900388</a> and at <a href="https://www.instagram.com/about/legal/privacy/">https://www.instagram.com/about/legal/privacy/</a>.
                            </p>
                            <h3>LinkedIn</h3>
                            <p>We have integrated components of LinkedIn into this website. LinkedIn is an Internet-based social network that enables users to connect with existing business contacts and make new business contacts. Over 400 million registered people use LinkedIn in more than 200 countries. This makes LinkedIn currently the largest platform for business contacts and one of the most visited websites in the world.</p>
                            <p>LinkedIn is operated by LinkedIn Corporation, 2029 Stierlin Court Mountain View, CA 94043, USA. Privacy matters outside the USA are handled by LinkedIn Ireland, Privacy Policy Issues, Wilton Plaza, Wilton Place, Dublin 2, Ireland.</p>
                            <p>Each time part of our website is accessed that features a LinkedIn component (LinkedIn plug-in), this component prompts the browser used by the data subject to download a corresponding representation of the LinkedIn component. More information about LinkedIn plug-ins is available at <a href="https://developer.linkedin.com/plugins">https://developer.linkedin.com/plugins</a>. As part of this technical process, LinkedIn is informed about which specific subpage of our website is visited by the data subject.
                            </p>
                            <p>If the data subject is signed in to LinkedIn at the same time, LinkedIn recognises which specific subpage of our website the data subject visits each time the data subject accesses our website and for the entire duration of the respective visit. This information is collected by the LinkedIn component and assigned by LinkedIn to the respective LinkedIn account of the data subject. If the data subject clicks a LinkedIn button integrated into our website, LinkedIn assigns this information to the personal LinkedIn user account of the data subject and stores this personal data.</p>
                            <p>LinkedIn is always informed via the LinkedIn component that the data subject has visited our website if the data subject is signed in to LinkedIn at the same time as accessing our website; this takes place regardless of whether the data subject clicks the LinkedIn component or not. If the data subject does not want this information to be transmitted to LinkedIn, they can prevent it from being transmitted by signing out of their LinkedIn account before accessing our website.</p>
                            <p>LinkedIn provides the option of unsubscribing from email messages, text messages and targeted advertising and of managing ad settings at <a href="https://www.linkedin.com/psettings/guest-controls">https://www.linkedin.com/psettings/guest-controls</a>. LinkedIn also uses partners such as Quantcast, Google Analytics, BlueKai, DoubleClick, Nielsen, Comscore, Eloqua and Lotame, who can set cookies. Such cookies can be blocked at <a href="https://www.linkedin.com/legal/cookie-policy">https://www.linkedin.com/legal/cookie-policy</a>. The current LinkedIn privacy policy is available at <a href="https://www.linkedin.com/legal/privacy-policy">https://www.linkedin.com/legal/privacy-policy</a>. The LinkedIn cookie policy is available at <a href="https://www.linkedin.com/legal/cookie-policy">https://www.linkedin.com/legal/cookie-policy</a>.
                            </p>
                            <h3>Twitter</h3>
                            <p>We have integrated components of Twitter into this website. Twitter is a multilingual, publicly accessible microblogging service where users can publish and spread "tweets", i.e. short messages limited to 280 characters. These short messages can be accessed by anyone, including people who are not signed in to Twitter. The tweets are also displayed to followers of the respective user. Followers are other Twitter users who follow a user's tweets. Twitter also allows you to communicate with a wide audience using hashtags, links or retweets.</p>
                            <p>Twitter is operated by Twitter, Inc., 1355 Market Street, Suite 900, San Francisco, CA 94103, USA.</p>
                            <p>Each time one of the individual pages of this website is accessed, which is operated by us and incorporates a Twitter component (Twitter button), the web browser on the data subject's IT system is automatically prompted by the respective Twitter component to download a representation of the corresponding Twitter component from Twitter. More information about Twitter buttons is available at <a href="https://publish.twitter.com/">https://publish.twitter.com/</a>. As part of this technical process, Twitter is informed about which specific subpage of our website is visited by the data subject. The purpose of integrating the Twitter component is to enable users to spread the content of this website, to make this website known in the digital world and to increase visitor numbers.
                            </p>
                            <p>If the data subject is signed in to Twitter at the same time, Twitter recognises which specific subpage of our website the data subject visits each time the data subject accesses our website and for the entire duration of the respective visit. This information is collected by the Twitter component and assigned by Twitter to the respective Twitter account of the data subject. If the data subject presses one of the Twitter buttons integrated into our website, the data and information thus transmitted will be assigned to the personal Twitter user account of the data subject and stored and processed by Twitter.</p>
                            <p>Twitter is always informed via the Twitter component that the data subject has visited our website if the data subject is signed in to Twitter at the same time as accessing our website; this takes place regardless of whether the data subject clicks the Twitter component or not. If the data subject does not want this information to be transmitted to Twitter, they can prevent it from being transmitted by logging out of their Twitter account before accessing our website.</p>
                            <p>The current Twitter privacy policy is available at <a href="https://twitter.com/en/privacy">https://twitter.com/en/privacy</a>.</p>
                            <h3>Xing</h3>
                            <p>We have integrated components of Xing into this website. Xing is an Internet-based social network that enables users to connect with existing business contacts and make new business contacts. Individual users can create their own personal Xing profile. Companies can use Xing to create company profiles or publish job vacancies, for example.</p>
                            <p>Xing is operated by XING SE, Dammtorstraße 30, 20354 Hamburg, Germany.</p>
                            <p>Each time one of the individual pages of this website is accessed, which is operated by us and incorporates a Xing component (Xing plug-in), the web browser on the data subject's IT system is automatically prompted by the respective Xing component to download a representation of the corresponding Xing component from Xing. More information about Xing plug-ins is available at <a href="https://dev.xing.com/plugins">https://dev.xing.com/plugins</a>. As part of this technical process, Xing is informed about which specific subpage of our website is visited by the data subject.
                            </p>
                            <p>If the data subject is signed in to Xing at the same time, Xing recognises which specific subpage of our website the data subject visits each time the data subject accesses our website and for the entire duration of the respective visit. This information is collected by the Xing component and assigned by Xing to the respective Xing account of the data subject. If the data subject presses one of the Xing buttons integrated into our website, for example the "Share" button, Xing assigns this information to the personal Xing user account of the data subject and stores this personal data.</p>
                            <p>Xing is always informed via the Xing component that the data subject has visited our website if the data subject is signed in to Xing at the same time as accessing our website; this takes place regardless of whether the data subject clicks the Xing component or not. If the data subject does not want this information to be transmitted to Xing, they can prevent it from being transmitted by signing out of their Xing account before accessing our website.</p>
                            <p>The privacy policy published by Xing, available at <a href="https://www.xing.com/privacy">https://www.xing.com/privacy</a>, provides information about the collection, processing and use of personal data by Xing. Xing has also published a privacy policy for the XING Share button at <a href="https://www.xing.com/app/share?op=data_protection">https://www.xing.com/app/share?op=data_protection</a>.
                            </p>
                            <h2>11. Other services</h2>
                            <p>Other services that we use are:</p>
                            <h3>Disqus-Kommentierungsfunktion</h3>
                            <p>This website uses the Disqus comment function provided by Disqus, Inc., 301 Howard Street, Suite 300, San Francisco, CA 94105, USA (hereinafter "Disqus"). Disqus is an interactive comment system that enables registered users, with just a single sign-on, to comment on all websites that use Disqus. Disqus allows users to sign in via existing Facebook (via Facebook Connect) Twitter and Google+ accounts. If you sign in via your Facebook, Twitter or Google+ account, data might also be collected, stored and used by these providers. Details on this can be found in the privacy policy of the respective provider. The comment function can also be used without registration, as a "guest". Some functions are not, however, available to guests.</p>
                            <p>Alongside the comment text, Disqus transmits your email address and IP address to us. We need the comment text to be able to publish it. We need the other information only for the purpose of getting in touch regarding your use of Disqus, for example if we have any questions about your user comment, or to prevent liability and misuse. To prevent liability for comment content, it can also be necessary for [WEBSITE] to delete comments, to exclude comments from publication or – as a less severe measure and being labelled accordingly – to edit them.</p>
                            <p>With regard to the collection, processing and use of relevant data by Disqus and your rights in this respect, the privacy policies of Disqus, available at <a href="http://docs.disqus.com/help/30/">http://docs.disqus.com/help/30/</a> and <a href="http://docs.disqus.com/help/29/">http://docs.disqus.com/help/29/</a>, apply.
                            </p>
                            <h2>12. Integration of third-party providers</h2>
                            <p>In order to illustrate and optimise our offering, services from the third-party providers listed below are integrated in our webpages. This includes in particular video and audio players, but also other embedded and suitably identified content and partner modules, such as weather and maps, job markets, property, currency converters and competitions. In this respect we collect no personal data whatsoever, nor do we transmit any to the third-party providers. Where these types of services are integrated, your browser routinely establishes a direct connection to the servers of the third-party provider and transmits data to the provider, even when content is simply loaded and displayed. In this regard we have no influence on their data processing operations nor do we have any knowledge of the full extent of data collection, the purposes of collection or the storage periods. In general, however, the only data concerned is the user’s IP address, without which the third-party provider would not be able to send the embedded content to the browser of the user in question. The IP address is therefore required in order for this content to be displayed.</p>
                            <p>Please visit the webpages of the third-party provider in question to find out about their data privacy policy.</p>
                            <h3>Facebook (Facebook Ireland Limited, 4 Grand Canal Square, Dublin 2, Ireland)</h3>
                            <a href="https://de-de.facebook.com/about/privacy/">https://de-de.facebook.com/about/privacy/</a><p></p>
                            <h3>Instagram (Facebook Ireland Limited, 4 Grand Canal Square, Dublin 2, Ireland)</h3>
                            <a href="https://www.instagram.com/legal/privacy/">https://www.instagram.com/legal/privacy/</a><p></p>
                            <h3>LinkedIn (LinkedIn Corporation, 2029 Stierlin Court Mountain View, CA 94043, USA)</h3>
                            <a href="https://www.linkedin.com/legal/privacy-policy">https://www.linkedin.com/legal/privacy-policy</a><p></p>
                            <h3>Twitter (Twitter Inc., 1355 Market Street, Suite 900, San Francisco, CA 94103, USA)</h3>
                            <a href="https://twitter.com/privacy?lang=de">https://twitter.com/privacy?lang=de</a><p></p>
                            <h3>Xing (XING SE, Dammtorstrasse 30, 20354 Hamburg, Germany)</h3>
                            <a href="https://www.xing.com/privacy">https://www.xing.com/privacy</a><p></p>
                            <h2>13. Storage duration</h2>
                            <p>We only store personal data as long as we are authorised to do so and as long as the purpose of processing is still relevant. Statutory retention periods govern how long personal data is stored for. Once this period has expired, the corresponding data is routinely erased, provided it is no longer needed to initiate or perform a contract.</p>
                            <h2>14. Contact details and your rights as a data subject</h2>
                            <p>Should you have any queries or comments on data protection and privacy or wish to exercise your rights as a data subject, please contact our data protection officer at any time:</p>
                            <address>Axel Springer Ideas Engineering GmbH<br/>
                                Datenschutz<br/>
                                Axel Springer Str. 65<br/>
                                10969 Berlin<br/>
                                <a href="mailto:datenschutz@asideas.de">datenschutz@asideas.de</a>
                            </address>
                            <h3>Information and rectification</h3>&gt;
                            <p>You can receive information at any time and at no charge about whether we are processing personal data related to you and also about which information we are specifically storing about you. You are also entitled to receive a copy of the stored information. You can also have errors in your data corrected and missing information completed.</p>
                            <h3>Erasure, restriction of processing and “right to be forgotten”</h3>&gt;
                            <p>You can request that your data be erased and its processing restricted. Please note that statutory retention obligations are in effect for contracts relating to paid services (such as the purchase of a subscription to Axel Springer Crowd) and that we will therefore not always be able to fully erase your data completely in all cases. In this case, your data will be labelled to the effect that future processing should be restricted.</p>
                            <h3>Data portability</h3>
                            <p>Where applicable, you also have the right to have your personal data transmitted to you or to another data controller in a structured, standardised and machine-readable format, as long as processing is performed on the basis of consent or contract using automated procedures. This does not apply, however, where the processing is necessary for the performance of a task carried out in the public interest or in the exercise of official authority vested in the controller. You also have the right to have the personal data transmitted directly from one data controller to another, provided that it is technically feasible to do so and does not infringe upon the rights and freedoms of other persons.</p>
                            <h3>Withdrawal of consent, objecting to processing </h3>
                            <p>You can withdraw your previously-given consent at any time with effect for the future by contacting the aforementioned address. In particular, you may express your objection in writing or via electronic text communication media at crowd@asideas.de or Axel-Springer-Str. 65 in 10969 Berlin regarding the use of your email address for the purpose of newsletter delivery with effect for the future without incurring any transmission costs beyond the base costs imposed by your provider. </p>
                            <p>Moreover, you have the right to object to the processing of your personal data at any time (where such processing is based on a legitimate or public interest) for reasons arising from your particular circumstances. This also applies to profiling activities based on these provisions. If such an objection is received, we will cease to process the personal data unless we can demonstrate compelling legitimate grounds for the processing that override the interests, rights and freedoms of the data subject, of if the processing is for the establishment, exercise or defence of legal claims.</p>
                            <p>If we are processing personal data for the purpose of direct marketing, you have the right to object to the processing of your personal data at any time for the purpose of such marketing by contacting the aforementioned address. This also applies to profiling insofar as it is connected with such direct marketing. You also have the right to file an objection for reasons arising from your particular circumstances against processing of your personal data that we are engaged in for scientific, historical research or statistical purposes, unless such processing is required to perform a task that is in the public interest.</p>
                            <h3>Right of complaint</h3>
                            <p>You also have the right to submit a complaint to the competent supervisory authority and to seek legal remedies. The supervisory authority to whom the complaint was submitted will notify the complainant about the status and result of their complaint, including the option of seeking a legal remedy through a court of law.</p>
                            <h3>Right of complaint</h3>
                            <p>We do not perform any automated decision-making or profiling.</p>
                            <i>Last revised: June 11, 2019</i></div>
                    </content-row>
                </div>
            </div>
        )
    }

}

export default PrivacyView
